Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2023-04, with the labels that each got.

#55 🐛 Fix make target for release note generation
  Makefile
  config/samples/cloud-provider-azure.yaml
Labels: cncf-cla: yes, approved, size/S

#58 :bug: Fix follow up bug with release notes make target
  Makefile
Labels: cncf-cla: yes, approved, size/XS

#59 🐛 Fix release draft GitHub action
  .github/workflows/release.yml
Labels: cncf-cla: yes, approved, size/XS

#64 ✨ Add watch to HelmChartProxy for Cluster creation and updates
  controllers/helmchartproxy/helmchartproxy_controller.go
Labels: cncf-cla: yes, approved, size/M

#60 :sparkles:Add support for the matchExpressions field in the label selector
  controllers/helmchartproxy/helmchartproxy_controller.go
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/XS

#66 🐛 Retry upgrades on failed releases and fix status and requeue bug
  api/v1alpha1/condition_consts.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  internal/helm_operations.go
Labels: size/L, cncf-cla: yes, approved

#67 🌱 Use string join function in cloud provider azure chart
  config/samples/cloud-provider-azure.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS
