Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2023-01, with the labels that each got.

#7 Revert ":seedling: Bump helm.sh/helm/v3 from 3.10.0 to 3.11.0"
  go.mod
  go.sum
Labels: size/L, cncf-cla: yes, approved

#11 📖 Add logos and update README
  README.md
  logos/LICENSE.md
  logos/README.md
  logos/icons/CAPI icons.ai
  logos/icons/README.md
  logos/icons/cluster.png
  logos/icons/cluster.svg
  logos/icons/machine-deployment.png
  logos/icons/machine-deployment.svg
  logos/icons/machine-set.png
  logos/icons/machine-set.svg
  logos/icons/machine.png
  logos/icons/machine.svg
  logos/kubernetes-cluster-logos_1.pdf
  logos/kubernetes-cluster-logos_2.pdf
  logos/kubernetes-cluster-logos_final-01.svg
  logos/kubernetes-cluster-logos_final-02.svg
Labels: cncf-cla: yes, size/XL, approved

#9 📖 Add doc comments for functions
  api/v1alpha1/condition_consts.go
  api/v1alpha1/helmchartproxy_types.go
  api/v1alpha1/helmreleaseproxy_types.go
  controllers/helmchartproxy/helmchartproxy_controller.go
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  internal/cluster_operations.go
  internal/helm_operations.go
  internal/value_substitutions.go
  main.go
Labels: size/L, cncf-cla: yes, approved

#12 Create metallb helmchartproxy example
  config/samples/metallb.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S
