Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2023-08, with the labels that each got.

#105 🌱 Update CAPI and controller-runtime deps
  api/v1alpha1/helmchartproxy_webhook.go
  api/v1alpha1/helmreleaseproxy_webhook.go
  controllers/helmchartproxy/helmchartproxy_controller.go
  controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
  controllers/helmchartproxy/helmchartproxy_controller_test.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XL, approved, lgtm

#109 🌱 Set default log level to 2
  main.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#108 ✨ Add git version info to controller
  hack/version.sh
  main.go
  version/version.go
Labels: cncf-cla: yes, approved, lgtm, size/M
