Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2023-03, with the labels that each got.

#33 :book: DOCS: Fix remote repo url
  docs/quick-start.md
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/XS

#14 Automatic installation of Calico on workload clusters
  config/samples/calico-cni.yaml
  docs/development.md
  hack/setup-calico-autoinstallation.sh
Labels: cncf-cla: yes, ok-to-test, size/M

#35 :sparkles: Add leader election lease related flags
  main.go
Labels: cncf-cla: yes, ok-to-test, lgtm, size/S

#41 :seedling: Fix registry URL, image name, and job scripts
  Makefile
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_pull_policy.yaml
  config/samples/metallb.yaml
  hack/verify-container-images.sh
  hack/version.sh
  scripts/ci-e2e-lib.sh
Labels: cncf-cla: yes, approved, size/M

#42 :seedling: Fix incorrect references in Makefile and project maintainer script
  Makefile
  config/default/manager_image_patch.yaml
  hack/get-project-maintainers.sh
Labels: cncf-cla: yes, approved, size/M

#36 :seedling: Update cloud-provider-azure sample version
  config/samples/cloud-provider-azure.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/XS

#46 :seedling: Fix alias in ./hack/get-project-maintainers.sh script and bump kpromo version
  Makefile
  hack/get-project-maintainers.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#49 🌱 Add deployment make target and files for GitHub release actions
  Makefile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  metadata.yaml
  tilt-provider.yaml
Labels: cncf-cla: yes, approved, size/M

#51 🌱 Add make target for release metadata
  Makefile
  metadata.yaml
Labels: cncf-cla: yes, approved, size/XS

#52 🌱 Rename module to sigs.k8s.io/cluster-api-addon-provider-helm
  controllers/helmchartproxy/helmchartproxy_controller.go
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmchartproxy/suite_test.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  controllers/helmreleaseproxy/suite_test.go
  go.mod
  internal/helm_operations.go
  internal/value_substitutions.go
  main.go
Labels: cncf-cla: yes, approved, size/S
