Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2024-05, with the labels that each got.

#203 🌱 Bump CAPI to v1.7.1
  Makefile
  go.mod
  go.sum
  internal/value_substitutions.go
  test/e2e/config/helm.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: area/dependency, cncf-cla: yes, kind/cleanup, size/XL, approved, lgtm

#240 ✨ Add yaml CI validation for yml\yaml files
  .github/workflows/yamlvalidator.yml
  .github/yamllint_config.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/M

#237 🌱 Bump CAPI to v1.7.2
  go.mod
  go.sum
  test/e2e/config/helm.yaml
Labels: cncf-cla: yes, kind/cleanup, approved, lgtm, size/M

#238 :sparkles: Add support for specifying TLS config including custom CA certificates
  api/v1alpha1/condition_consts.go
  api/v1alpha1/helmchartproxy_types.go
  api/v1alpha1/helmreleaseproxy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
  controllers/suite_test.go
  internal/helm_client.go
  internal/mocks/helm_client_mock.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#251 :seedling: Add log options from k8s.io/component-base/logs
  go.mod
  main.go
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S
