Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2024-06, with the labels that each got.

#252 :bug: Fix OCI client configuration logic
  internal/helm_client.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#253 :bug: pointer checks if user doesn't specify CASecret
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#256 📖 Update README.md
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/M

#260 🌱 Bump CAPI to v1.7.3
  go.mod
  go.sum
  test/e2e/config/helm.yaml
Labels: cncf-cla: yes, kind/cleanup, approved, lgtm, size/M

#255 🌱 Use envtest binaries from controller-tools repo
  Makefile
Labels: cncf-cla: yes, kind/cleanup, approved, lgtm, size/XS
