Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2024-02, with the labels that each got.

#163 🐛 Use local kind registry by default in e2e tests
  Makefile
  scripts/ci-e2e.sh
Labels: cncf-cla: yes, approved, lgtm, size/S

#162 🐛 Bump Go version to v1.21 in GitHub actions
  .github/workflows/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#165 ✨ Add CAPI API version upgrade test
  Makefile
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/helm.yaml
  test/e2e/data/addons-helm/v1.5/bases/calico.yaml
  test/e2e/data/addons-helm/v1.5/bases/cluster-with-kcp.yaml
  test/e2e/data/addons-helm/v1.5/bases/md.yaml
  test/e2e/data/addons-helm/v1.5/cluster-template.yaml
  test/e2e/data/addons-helm/v1.5/cluster-template/kustomization.yaml
  test/e2e/e2e_suite_vars.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#166 🌱 Add Matt Boersma to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, lgtm, size/XS

#161 🌱 Minor cleanup for e2e tests
  Makefile
  test/e2e/data/addons-helm/v1beta1/bases/calico.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_suite_vars.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#164 ✨ Add e2e test and template for K8s version upgrade
  Makefile
  test/e2e/capi_test.go
  test/e2e/config/helm.yaml
  test/e2e/data/addons-helm/v1beta1/bases/cluster-with-topology.yaml
  test/e2e/data/addons-helm/v1beta1/cluster-template-upgrades.yaml
  test/e2e/data/addons-helm/v1beta1/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/addons-helm/v1beta1/cluster-template.yaml
  test/e2e/data/addons-helm/v1beta1/clusterclass-quick-start.yaml
  test/e2e/data/kubetest/conformance.yaml
Labels: cncf-cla: yes, size/XL, approved, lgtm

#168 🌱 Convert pointer types in Helm options to regular fields
  api/v1alpha1/helmchartproxy_types.go
  api/v1alpha1/helmchartproxy_webhook.go
  api/v1alpha1/helmreleaseproxy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
  controllers/helmchartproxy/helmchartproxy_controller_test.go
  internal/helm_client.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#150 ✨ Add controllers tests for real Reconcile loop running with setup-envtest
  .gitignore
  Makefile
  controllers/controllers_test.go
  controllers/helmchartproxy/helmchartproxy_controller_test.go
  controllers/helmchartproxy/suite_test.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
  controllers/helmreleaseproxy/suite_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/kubeconfig.go
  internal/mocks/helm_client_mock.go
  internal/mocks/kubeconfig_mock.go
  main.go
  test/controllers/data/crd/cluster.x-k8s.io_clusters.yaml
Labels: size/XXL, cncf-cla: yes, approved, ok-to-test, lgtm

#169 🌱 Move CecileRobertMichon to emeritus approvers
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, approved, lgtm, size/S

#170 🌱 Bump CAPI dependencies to v1.6.1
  Makefile
  go.mod
  go.sum
  test/e2e/config/helm.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#171 ✨ Add e2e test to install and validate a Helm chart on a workload cluster
  Makefile
  test/e2e/common.go
  test/e2e/config/helm.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/helm_install.go
  test/e2e/helm_test.go
  test/e2e/helpers.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#173 ✨ Add e2e test spec to upgrade or reinstall a Helm chart on a Cluster
  test/e2e/common.go
  test/e2e/helm_install.go
  test/e2e/helm_test.go
  test/e2e/helm_upgrade.go
  test/e2e/helpers.go
Labels: size/L, cncf-cla: yes, approved, lgtm

#177 :bug: Add namespace when listing HelmReleaseProxies related to HelmChartProxy
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/XS
