Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2024-10, with the labels that each got.

#288 :sparkles: expose resetThenReuseValues upgrade option
  api/v1alpha1/helmchartproxy_types.go
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  internal/helm_client.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#296 🌱 Bump CAPI to v1.8.4
  Makefile
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/M

#302 ✨ Update golangci-lint version and fix related linting issues
  .github/workflows/golangci-lint.yml
  controllers/helmchartproxy/helmchartproxy_controller.go
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
Labels: cncf-cla: yes, approved, tide/merge-method-squash, ok-to-test, lgtm, size/M
