Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2024-04, with the labels that each got.

#181 🌱 Replace deprecated call to klogr.NewWithOptions
  controllers/suite_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#207 🐛 Fix missing minor version in metadata.yaml
  metadata.yaml
  test/e2e/config/helm.yaml
  test/e2e/data/shared/v1beta1-provider/metadata.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#208 ✨ Add visualizer label patch for HelmChartProxy and HelmReleaseProxy
  config/crd/patches/visualizer_label_in_helmchartproxies.yaml
  config/crd/patches/visualizer_label_in_helmreleaseproxies.yaml
Labels: cncf-cla: yes, approved, lgtm, size/S

#211 🐛 Add visualizer label patch to kustomization.yaml
  config/crd/kustomization.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#205 📖 Add release process documentation
  docs/releasing.md
Labels: kind/documentation, cncf-cla: yes, approved, lgtm, size/M

#213 🌱 Bump CAPI to v1.6.4
  go.mod
  go.sum
  test/e2e/config/helm.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#219 🐛 Remove extra key in metadata.yaml
  metadata.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#222 🌱 add explicit securityContext the CAAPH deployment
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S

#223 🐛 Fix TestReconcileForCluster unit test
  controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XS
