Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2024-01, with the labels that each got.

#136 ✨ feat(helm release): use custom creds for private OCI
  Makefile
  api/v1alpha1/condition_consts.go
  api/v1alpha1/helmchartproxy_types.go
  api/v1alpha1/helmreleaseproxy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
  controllers/helmchartproxy/helmchartproxy_controller_test.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
  docs/quick-start.md
  go.mod
  go.sum
  internal/helm_client.go
  internal/mocks/helm_client_mock.go
Labels: size/XXL, cncf-cla: yes, approved, ok-to-test, lgtm

#148 🐛 Fix nil pointer bug in EnableClientCache option
  api/v1alpha1/helmchartproxy_webhook.go
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
  internal/helm_client.go
  main.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#143 🌱 Bump CAPI to v1.6, Helm to v3.13.3, and controller-runtime to v0.16.3
  Makefile
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  internal/kubeconfig.go
  main.go
Labels: size/XXL, cncf-cla: yes, approved, lgtm

#147 ✨ Implement e2e integration testing by using CAPI v1.6 test framework
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/common-vars.sh
  hack/gen-flavors.sh
  scripts/ci-e2e.sh
  test/e2e/capi_test.go
  test/e2e/common.go
  test/e2e/config/helm.yaml
  test/e2e/data/addons-helm/v1beta1/bases/calico.yaml
  test/e2e/data/addons-helm/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/addons-helm/v1beta1/bases/md.yaml
  test/e2e/data/addons-helm/v1beta1/cluster-template.yaml
  test/e2e/data/addons-helm/v1beta1/cluster-template/kustomization.yaml
  test/e2e/data/shared/v1beta1-provider/metadata.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_suite_vars.go
  test/e2e/helpers.go
  test/e2e/log.go
Labels: size/XXL, cncf-cla: yes, approved, lgtm
