Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2025-04, with the labels that each got.

#382 :seedling: Fix missing Metadata kind in metadata.yaml
  metadata.yaml
  test/e2e/data/shared/v1beta1-provider/metadata.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#363 🌱 Add rest config options (kube-api-qps & kube-api-burst)
  main.go
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S

#372 :sparkles: Replace deprecated gcr.io/kubebuilder/kube-rbac-proxy
  config/default/manager_auth_proxy_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manager/metrics_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
Labels: cncf-cla: yes, approved, lgtm, size/M

#383 🌱 Bump CAPI to v1.9.6
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/S

#389 🐛 fix: add registry client TLS connection idle timeout
  internal/helm_client.go
  internal/helm_client_test.go
  internal/testdata/ca-bundle.pem
Labels: size/L, cncf-cla: yes, approved, ok-to-test, lgtm
