Repository kubernetes-sigs/cluster-api-addon-provider-helm, pull requests merged in 2025-01, with the labels that each got.

#337 🌱 Bump CAPI to v1.8.8
  go.mod
  go.sum
  test/e2e/config/helm.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: cncf-cla: yes, kind/cleanup, approved, lgtm, size/M

#328 ✨ Skip reconciliation if deleting cluster
  controllers/helmchartproxy/helmchartproxy_controller_phases.go
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/S

#338 🌱 Bump CAPI to v1.9.3
  Makefile
  config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
  config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
  config/rbac/role.yaml
  controllers/helmchartproxy/helmchartproxy_controller.go
  controllers/helmreleaseproxy/helmreleaseproxy_controller.go
  go.mod
  go.sum
  internal/value_substitutions.go
  test/e2e/config/helm.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: size/L, cncf-cla: yes, kind/cleanup, approved, lgtm

#330 :sparkles: Able to build provider docker without Makefile and Dockerfile modifications
  Dockerfile
  Makefile
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/M

#340 :seedling: Download Cluster API CRDs for every integration test
  Makefile
  config/manager/manager.yaml
  controllers/suite_test.go
  test/controllers/data/crd/cluster.x-k8s.io_clusters.yaml
Labels: size/XXL, cncf-cla: yes, approved, ok-to-test, lgtm

#342 🐛 Fix golang version getter bash script in Makefile
  Makefile
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/XS

#346 🌱 Bump Helm version to v3.16.4
  go.mod
  go.sum
Labels: size/L, cncf-cla: yes, approved, lgtm

#347 🌱 Bump CAPI to v1.9.4
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, lgtm, size/S

#354 :bug: Update metadata for v0.3.0 release
  metadata.yaml
Labels: cncf-cla: yes, approved, ok-to-test, lgtm, size/XS
